// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltjbnZIMwsTyjtM0cUSAnf1jHfAu5Ark',
    appId: '1:935761986596:android:edbe015760da4f0e9184b1',
    messagingSenderId: '935761986596',
    projectId: 'sae-5-groupegoat',
    databaseURL:
        'https://sae-5-groupegoat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sae-5-groupegoat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRZaK4ubN1GC_2L4KWutY90z82JS7F5s',
    appId: '1:935761986596:ios:58cb2cf5baebf09a9184b1',
    messagingSenderId: '935761986596',
    projectId: 'sae-5-groupegoat',
    databaseURL:
        'https://sae-5-groupegoat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sae-5-groupegoat.appspot.com',
    androidClientId:
        '935761986596-ghhjbrhv1av3nnttf3cvm97snojgok20.apps.googleusercontent.com',
    iosClientId:
        '935761986596-eihqhhpjn2jhide7ocgv1vjfe54ufap7.apps.googleusercontent.com',
    iosBundleId: 'com.ckoitgrol.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJSaXU5HK9eWA4nv3fj6shaJIYaos2RE',
    appId: '1:935761986596:web:7bc5911f21ecb8c99184b1',
    messagingSenderId: '935761986596',
    projectId: 'sae-5-groupegoat',
    authDomain: 'sae-5-groupegoat.firebaseapp.com',
    databaseURL:
        'https://sae-5-groupegoat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sae-5-groupegoat.appspot.com',
    measurementId: 'G-9GXVSF4MW4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRJSaXU5HK9eWA4nv3fj6shaJIYaos2RE',
    appId: '1:935761986596:web:837ca5b661a44e4c9184b1',
    messagingSenderId: '935761986596',
    projectId: 'sae-5-groupegoat',
    authDomain: 'sae-5-groupegoat.firebaseapp.com',
    databaseURL:
        'https://sae-5-groupegoat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sae-5-groupegoat.appspot.com',
    measurementId: 'G-EXCWXN72ET',
  );
}
