name: ckoitgrol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  internet_connection_checker: ^1.0.0+1
  intl: any
  flutter_localization: ^0.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  open_mail_app: ^0.4.5
  url_launcher: ^6.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true

  uses-material-design: true

  fonts:
    - family: TheBomb
      fonts:
        - asset: assets/fonts/TheBomb.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  assets:
    - assets/images/
  #   - assets/tab_1.png
  #   - assets/tab_2.png
  #   - assets/tab_3.png
  #   - assets/tab_4.png
  #   - assets/tab_1s.png
  #   - assets/tab_2s.png
  #   - assets/tab_3s.png
  #   - assets/tab_4s.png
